# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12product_info.proto\x12\x0bproductinfo\"G\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\"\x1a\n\tProductID\x12\r\n\x05value\x18\x01 \x01(\t\"\x18\n\nProductDel\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc9\x01\n\x0bProductInfo\x12:\n\naddProduct\x12\x14.productinfo.Product\x1a\x16.productinfo.ProductID\x12:\n\ngetProduct\x12\x16.productinfo.ProductID\x1a\x14.productinfo.Product\x12\x42\n\ndelProduct\x12\x17.productinfo.ProductDel\x1a\x1b.productinfo.DeleteResponseB\rZ\x0bproductinfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013productinfo'
  _globals['_PRODUCT']._serialized_start=35
  _globals['_PRODUCT']._serialized_end=106
  _globals['_PRODUCTID']._serialized_start=108
  _globals['_PRODUCTID']._serialized_end=134
  _globals['_PRODUCTDEL']._serialized_start=136
  _globals['_PRODUCTDEL']._serialized_end=160
  _globals['_DELETERESPONSE']._serialized_start=162
  _globals['_DELETERESPONSE']._serialized_end=195
  _globals['_PRODUCTINFO']._serialized_start=198
  _globals['_PRODUCTINFO']._serialized_end=399
# @@protoc_insertion_point(module_scope)
